### ISSUE TITLE
Provide Template URL

### ISSUE THREAD

**Issue by 1oglop1** [aws-samples/aws-cloudhsm-cloudformation-template#7]
Hi, since this is a CloudFormation it would be nice to have the template URL associated with the current commit SHA for easier deployment.
The reason is that `cloudhsm.yaml` is larger than 50kB, resulting in `at 'templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200`

**Comment by palmep** [comment]
Can you confirm that you're attempting to use `aws cloudformation validate-template` API, or via CDK?
What steps are you taking to get this error?

The operation to validate the URL (for files larger than 51,200 bytes) of a template only works on objects stored in S3, rather than this GitHub repo. 
If you're looking for a permanent link to the `cloudhsm.yaml` file, you can follow [this documentation](https://docs.github.com/en/repositories/working-with-files/using-files/getting-permanent-links-to-files).

**Comment by 1oglop1** [comment]
@palmep What I meant is that this repository could provide S3 URL as part of release notes.
So the consumer can use it directly without uploading themselves. 
See https://bucketav.com/help/release-notes/ for example.

**Comment by palmep** [comment]
Due to this being a sample, we recommend that customers download the template and modify it for their particular use case, rather than using "as-is". This is intentional due to the nature of CloudHSM as a security product and the root of trust for many deployments. Feel free to fork this however and add your own template S3 URLs

**Comment by 1oglop1** [comment]
👍
